# Generated by Django 6.0.1 on 2026-01-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapresupuesto',
            old_name='precio_unitario',
            new_name='monto',
        ),
        migrations.RemoveField(
            model_name='lineapresupuesto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='estado',
        ),
        migrations.AddField(
            model_name='lineapresupuesto',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso (+)'), ('GASTO', 'Gasto (-)')], default='GASTO', max_length=10),
        ),
    ]
